import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";
import { FooterSimple } from "./components/FooterSimple";

const urbanist = Urbanist({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "concept.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="dark">
      <head>
        <link href={"/favicon.png"} rel={"icon"} sizes="any" />
      </head>
      <body className={urbanist.className}>
        {children}
        <MantineProvider>
          <FooterSimple />
        </MantineProvider>
      </body>
    </html>
  );
}
