import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Header from "./components/Header";
import { HeroParallaxDemo } from "./components/HeroParallax";
import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";
import { FooterSimple } from "./components/FooterSimple";
import { FeaturesGrid } from "./components/FeaturesGrid";
import { FloatingNavDemo } from "./components/FloatingNavDemo";
import { HeroHighlightDemo } from "./components/HeroHighlightDemo";
import { TextGenerateEffectDemo } from "./components/ TextGenerateEffectDemo";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Concept.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="dark">
      <body className={urbanist.className}>
        <FloatingNavDemo />
        {/* <Navbar /> */}
        <HeroHighlightDemo />
        {/* <Header /> */}
        <HeroParallaxDemo />
      
        <MantineProvider>
          <FeaturesGrid />
          <TextGenerateEffectDemo />
          <FooterSimple />
        </MantineProvider>
        {children}
      </body>
    </html>
  );
}
